<?php 
    $tooltip = new A25_Include_Tooltip();
    $tooltip->load();
?>
<style type="text/css">
h1 {
	margin-top: 20px;
    text-align: center;
    font-size: 40px;
    color: #006600;
}
h2 {
	font-size: 24px;
    text-align: center;
    margin-top: 32px;
    text-decoration: underline;
}
#frontpage_summary p {
		padding-left: 32px;
		padding-right: 32px;
		padding-top: 12px;
}
a.frontpage_button {
	display: inline-block;
	border: 1px solid black;
	padding: 12px 10px;
	width: 100%;
	text-align: center;
	text-decoration: none;
    background: <?php echo A25_DI::PlatformConfig()->colorScheme()->backgroundColor() ?> url(<?php echo ServerConfig::currentUrl() ?>/templates/aliveat25/images/calloutBG.png) repeat-x top center;
	color: white;
	font-weight: bold;
}
a.frontpage_button:hover {
	color: black;
	background: url(<?php echo ServerConfig::currentUrl() ?>/templates/aliveat25/images/buttonOn.jpg) repeat-x center;
    background-size: 100% 100%;
}
.frontpage_image {
    display: block;
    padding: 32px;
    margin-left: auto;
    margin-right: auto;
    max-width: 100%;
}
.reg {
    font-size: 9px;
}
</style>
<div id="frontpage_summary" style="
	color: black;
	border-left: 1px solid gray;
	border-right: 1px solid gray;
	border-top: 1px solid black;
	font-size: 14px;">
<div itemscope itemtype="https://schema.org/WebSite">
    <meta itemprop="url" content="https://www.californiasafedriver.com/"/>
    <meta itemprop="name" content="California Safe Driver"/>
</div>
<h1>California Safe Driver</h1>
<p style='text-align: center;'>
These Alive at 25<span class='reg' style='font-size: 10px;'>&reg;</span> and "ADoD" / Attitudinal Dynamics of Driving Courses* are
live, instructor led, interactive Zoom classes. DDC-4 and TDIC are self paced
courses.
</p>
<div class="row" style="margin: 5px 0px;">
  <div class="col-sm-6">
    <a class="frontpage_button" href="https://aliveat25.us/ca/find-a-course/">
      Alive at 25<span class='reg'>&reg;</span>
    </a>
  </div>
  <div class="col-sm-6">
    <a class="frontpage_button" href="https://adod.californiasafedriver.com/find-a-course">
      "ADoD" / Attitudinal Dynamics of Driving
    </a>
  </div>
</div>
<div class="row" style="margin: 5px 0px;">
  <div class="col-sm-6">
    <a class="frontpage_button" href="https://ddconline.californiasafedriver.com/DDC4">
      DDC-4 Online
    </a>
  </div>
  <div class="col-sm-6">
    <a class="frontpage_button" href="https://ddconline.californiasafedriver.com/component/option,com_course/task,confirm/course_id,17/Itemid,19/">
      "TDIC" Truck Driver Improvement Course
    </a>
  </div>
</div>
<div class="row" style="margin: 5px 0px;">
  <div class="col-sm-6">
    <a class="frontpage_button" href="https://ddconline.californiasafedriver.com/Modules">
        20-minute courses
    </a>
  </div>
  <div class="col-sm-6">
    <a class="frontpage_button" href="https://ddconline.californiasafedriver.com/espanol">
        Espa&ntilde;ol Alive at 25 / DDC-4
    </a>
  </div>
</div>
<p>
At California Safe Driver, we believe that when it comes to safe driving,
education and awareness save lives. That is why our highly trained public safety
professionals provide the National Safety Council's Defensive Driving Courses,
<b>Alive at 25<span class='reg' style='font-size: 18px;'>&reg;</span></b> and <b>"ADoD"</b> / <b>A</b>ttitudinal <b>D</b>ynamics <b>o</b>f <b>D</b>riving.
</p>
<h2>Why Is Our Online Learning So Effective?</h2>
<p>
After much research on how best to support an effective and interactive
curriculum to support our cognitive behavioral based courses, we have chosen to
incorporate the Kahoot! Program.
</p>
<p>
Evidence shows that impactful learning includes social, emotional, and academic
integration. That's why we facilitate curriculums utilizing an interactive,
cognitive behavior therapy based approach to learning. And we make them fun too!
</p>
<h2>How do we know what works?</h2>
<p>
We use the best law enforcement experienced, National Safety Council trained
facilitators, teach them how to use cognitive behavioral therapy strategies, and
create a highly interactive classroom community. Students become active
learners, and facilitators check learning throughout the class. Our well trained
and experienced facilitators are sensitive to the students' learning process,
and care deeply about their success. Additionally, at the conclusion of each
course, we check students' knowledge and engage them in anonymous open ended
course evaluations. These evaluations are used to continually monitor the
courses' success in helping students identify and change their behaviors; as
well as reveal any areas where we may need to improve.
</p>
<p style="text-align: center; color: #000066; font-size: 24px;">
Other programs may teach the class, we facilitate the learning.
</p>
<h2>LEARNING THEORY:</h2>
<p>
Kahoot! draws upon ideas from the Self-Determination Theory (SDT) of motivation,
developed by Richard Ryan, PhD and Edward Deci, PhD. SDT states that there are
two different types of motivation, extrinsic and intrinsic. Intrinsic motivation
takes place when an individual engages in an activity because they find it truly
enjoyable, whereas extrinsic motivation takes place when an individual engages
in an activity to achieve an outcome (for example to receive a reward, good
grades, money, etc.). Kahoot! incorporates both types of motivation in its
design. If you would like to read more about the successes of Kahoot! Then
please follow <a href="https://kahoot.com/research-articles/">this link</a>.
</p>
<h2>What Participants Will Learn in Alive at 25<span class='reg'>&reg;</span></h2>
<p>
Alive at 25<span class='reg'>&reg;</span> incorporates Reality Therapy and Choice&trade; Theory techniques to help
participants identify the five basic needs that drive human behavior: survival,
love and belonging, fun, freedom and power.
</p>
<p>
Whereas driver education teaches the mechanics of car and road handling and
state law, Alive at 25<span class='reg'>&reg;</span> focuses on inexperience, distractions, poor judgment,
peer pressure, a tendency to underestimate risk, decision making and
consequences. This driver safety course provides tools for making positive
choices in a way teens can relate to.
</p>
<h2>"ADoD" / Attitudinal Dynamics of Driving</h2>
<p>
Based on the cognitive behavioral therapy developments of Dr. Willian Glasser
and his book, <u>Choice Theory</u>, Attitudinal Dynamics of Driving is an 8-hour
diversion program designed to help participants make a direct connection between
their attitude and their choice to make poor decisions. They will learn how to
take responsibility for their actions, and see how the choices they make have
financial, legal, and personal consequences. The course guides participants to
ask questions, share opinions and join in non-threatening, non-judgmental
discussions. Attitudinal Dynamics of Driving is used extensively for court
referrals, and also as a diversion program for people with DUI violations,
excessive points, or any violation of law including minor alcohol violations.
<i>This course includes a self assessment survey and action plan to change behavior.</i>
</p>
<h2>"TDIC" TRUCK DRIVER IMPROVEMENT COURSE
</h2>
<p>
"TDIC" is a specialized 5-hour National Safety Council (NSC) online course. It
consists of interactive learning, including the award-winning NSC Professional
Truck Driver Online Course, plus three separate modules addressing speed
management, fatigued driving, and adverse weather conditions. "TDIC" examines
the most common causes of truck-related crashes and violations, and educates
truck drivers to make safe and lawful decisions. Content adjusts to the driver's
profile, type of vehicle driven, risk-level and driving conditions. "TDIC"
provides personalized, scenario-based training that helps students reflect on
their own driving experiences and challenges. Students can start and stop the
course whenever they wish, making it very convenient for professional truck
drivers. Tuition is $179.00.
</p>
<h2>DDC-4 Online (4-hour defensive driving course)</h2>
<p>
This is a highly-engaging course that has modernized content, a state-of-the-art
look and feel, and is highly interactive. The course was developed to be simple
and streamlined so each user is able to understand all life-saving concepts. The
course presents real-life driving situations, hazard recognition scenarios and
defensive driving techniques to motivate drivers to change risky driving habits
and behaviors to avoid collisions and traffic violations. The course features
adaptive curriculum tailored to the participant's profile, including age,
gender, driving behaviors and attitudes, vehicle and geographic location based
on a series of responses to questions asked throughout the course. Offered in
English and Spanish.
</p>
<h2 style="color: <?php echo A25_DI::PlatformConfig()->colorScheme()->backgroundColor() ?>">
Certificate of Completion
</h2>
<p>
<b>Alive at 25<span class='reg'>&reg;</span> & ADoD</b> students will be mailed their certificate of
completion after completing their course. <b>Allow a minimum of two weeks time
between your class and your court date to receive the certificate. You are 
responsible for presenting your certificate of completion to the court by your
due date.</b>
</p><p>
Students enrolling in the <b>Spanish DDC-4, DDC-4 or TDIC, it is your
responsibility to print your certificate at the end of your course and present
it to the court by your due date. (TDIC Course is 5 hours, made up of 4 classes.
Each class has a separate certificate that you must print and return to the
court.)</b> If you do not have access to a printer, email us for assistance at
info@californiasafedriver.com and provide us with your full name, date of birth,
phone number and address. Please note that certificates can take up to two weeks
to receive due to processing and mail delivery times.
</p>
<p style="font-size: 10px;">
* These National Safety Council Defensive Driving Courses save lives. However,
they are not recognized by the California Department of Motor Vehicles as
traffic school and are not considered point reduction courses. They may or may
not be recognized by some California insurance companies for premium discounts.
Please check with your individual insurance provider for information.
</p>
<h2 style="color: <?php echo A25_DI::PlatformConfig()->colorScheme()->backgroundColor() ?>">
Forgot your password or login?
</h2>
<p>
(Your zip code should be your password.) If you have forgotten your username
and/or password, please email us at <a href="mailto:<?php echo ServerConfig::adminEmailAddress;?>"><?php echo ServerConfig::adminEmailAddress;?></a> and provide us with:
<ul>
    <li>Your name</li>
    <li>Date of birth</li>
    <li>Phone number</li>
    <li>Name of the class that you need to complete</li>
</ul>
</p>
</div>
