<style type="text/css">
a.frontpage_button:link, a.frontpage_button:visited {
	background: none;
	background-color: <?=A25_DI::PlatformConfig()->colorScheme()->backgroundColor()?>;
}
a.frontpage_button {
	display: inline-block;
	border: 1px solid black;
	padding: 12px 10px;
	width: 160px;
	text-align: center;
	margin-right: 12px;
	text-decoration: none;
	background-color: <?php echo A25_DI::PlatformConfig()->colorScheme()->backgroundColor() ?> ;
	color: white;
	font-weight: bold;
    font-size: 14px;
        margin-top: 24px;
}
a.frontpage_button:hover {
	color: black;
	background: url(<?php echo ServerConfig::currentUrl() ?>/templates/aliveat25/images/buttonOn.jpg) repeat-x center;
}
.spab_orange {
	color: <?= A25_DI::PlatformConfig()->colorScheme()->backgroundColor() ?>;
}
p,li {
	color: #003f93;
	font-size: 16px;
}
</style>

<div style="padding: 24px; background-color: white;">
<div class="row">
<div class="col-sm-6">
<p class="spab_orange" style="font-size: 24px; font-style: italic; font-weight: bold;">Your T-01 Solution</p>
<ul>
    <li>SPAB and School Bus training provided by highly qualified & experienced State of California certified instructors</li>
    <li>Our instructors prepare applicants for their written and behind the wheel tests with the CHP</li>
</ul>
<p class="spab_orange" style="font-size: 24px;">We can help you with ~</p>
<ul>
    <li>Original SPAB and School Bus training</li>
    <li>Renewal training</li>
    <li>Required annual 10 hours of training</li>
    <li>Behind the Wheel Training</li>
    <li>Consulting</li>
    <li>Auditing training files</li>
    <li>Completing T-01&#39;s</li>
    <li>Driver management system development</li>
</ul>
<p class="spab_orange" style="font-size: 24px; font-weight: bold;">&#9733; T-01 Training certificates issued</h3>
</div>
    <div class="col-sm-6">
        <img src="<?php echo A25_Link::to('/templates/spab/images/bus.jpg'); ?>" border="0" alt="bus" style="max-width: 350px; width: 100%; max-height: 205px;"/>
<p style="text-align: center;">
  <a class="frontpage_button"
      href="<?=A25_Link::to('/find-a-course')?>">
    See Course Dates
  </a>
</p>
<p style="font-size: 20px; font-style: italic; text-align: center;">Call us to find out more about how we can best serve you, either at our location or yours</p>
<p class="spab_orange" style="font-size: 20px; font-weight: bold; text-align: center;"><?php echo PlatformConfig::phoneNumber ?></p>
<p style="font-style: italic; font-size: 11px;"><span class="spab_orange">SPAB</span>resources.com is a division of California Safe Driver, and is a member of the California Bus Association</p>
<img src="<?php echo A25_Link::to('/templates/spab/images/CBA.jpg'); ?>" border="0" alt="CBA" style="max-width: 321px; width: 100%; max-height: 229px;"/>
    </div>
</div>
</div>
