<p style="padding: 12px 0px;">
<a href="http://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?lawCode=VEH&division=6.&title=&part=&chapter=1.&article=1."
   style="background: none;">
    <img src="<?php echo A25_Link::to('images/CALegislature.png')?>"
         accesskey=""border="0" alt="California Legislature" width="724" height="84" /></a>
</p>
<p style="padding: 12px;">
<a href="https://www.chp.ca.gov/programs-services/programs/school-bus-program"
   style="background: none;">
    <img src="<?php echo A25_Link::to('images/CHP.png')?>"
         accesskey=""border="0" alt="California Highway Patrol" width="351" height="105" /></a>
</p>
<p style="padding: 12px;">
<a href="https://www.cde.ca.gov/ls/tn/ir/matrix.asp"
   style="background: none;">
    <img src="<?php echo A25_Link::to('images/CDE.gif')?>"
         accesskey=""border="0" alt="California Department of Education" width="200" height="105" /></a>
</p>
<p style="padding: 12px;">
<a href="https://www.dmv.ca.gov/portal/dmv/?1dmy&urile=wcm:path:/dmv_content_en/dmv/pubs/cdl_htm/sec1"
   style="background: none;">
    <img src="<?php echo A25_Link::to('images/CAgov.png')?>"
         accesskey=""border="0" alt="California Department of Motor Vehicles" width="96" height="74" /></a>
</p>
<p style="padding: 12px;">
<a href="https://www.uma.org/"
   style="background: none;">
    <img src="<?php echo A25_Link::to('images/uma-logo.png')?>"
         accesskey=""border="0" alt="United Motorcoach Association" width="413" height="84" /></a>
</p>
<p style="padding: 12px;">
<a href="https://www.buses.org/membership"
   style="background: none;">
    <img src="<?php echo A25_Link::to('images/ABA.png')?>"
         accesskey=""border="0" alt="American Bus Association" width="234" height="105" /></a>
</p>
<p style="padding: 12px;">
<a href="http://www.cbabus.com/"
   style="background: none;">
    <img src="<?php echo A25_Link::to('images/CBA.png')?>"
         accesskey=""border="0" alt="California Bus Association" width="151" height="117" /></a>
</p>
<p style="padding: 12px;">
<a href="https://www.napt.org/"
   style="background: none;">
    <img src="<?php echo A25_Link::to('images/NAPT.png')?>"
         accesskey=""border="0" alt="National Association for Pupil Transportation" width="330" height="116" /></a>
</p>
<p style="padding: 12px;">
<a href="https://www.castoways.org/"
   style="background: none;">
    <img src="<?php echo A25_Link::to('images/CASTO.jpg')?>"
         accesskey=""border="0" alt="Castoways" width="192" height="114" /></a>
</p>
<p style="padding: 12px;">
<a href="https://www.gcla.org/"
   style="background: none;">
    <img src="<?php echo A25_Link::to('images/GCLA.jpg')?>"
         accesskey=""border="0" alt="GCLA" width="360" height="100" /></a>
</p>
<p>SPABresources.com provides these links as a resource to you. It in no way should indicate this as any type of endorsement.</p>