<p>
The Mission of the ADoD program in Colorado is to encourage drivers of all ages
to adopt safe driving practices, take responsibility for their behavior, and to
be aware of typical driving hazards.
</p>

<h3>Program Parameters</h3>
<ul>
<li>Designed for drivers of all ages</li>
<li>A 6-hour classroom setting</li>
<li>There is no behind-the-wheel driving</li>
<li>Numerous scenario-based exercises with some role-playing</li>
<li>DVD-based learning with large and small group facilitation</li>
<li>Cost: $119.00</li>
<li>Designed to complement a standard driver education course and/or the Alive
At 25 course, or to provide new direction for drivers that incur traffic violations</li>
<li>There may be an insurance discount, check with your agent</li>
</ul>