<div class="locationContent">
<div class="colHeader">Become an Instructor / Start a Program</div>
<div align="center">
	<!-- <img src="http://aliveat25.us/images/headers/14.jpg" border="0" width="100" height="22" alt="14.jpg" /><br /> -->
	<div class="colHeaderPic"><img src="http://aliveat25.us/images/headers/14.jpg" border="0" alt="14.jpg" style="width: 100%;"/><br /></div>
</div>
<div id="colContent">
	<table border="0" cellspacing="0" cellpadding="0" class="contentpaneopen">
	<tr>
		<td valign="top" colspan="2">
		<p>The National Law Enforcement Curriculum (N.L.E.C.) Program of Alive at 25 is managed by and through an agreement between the National Safety Council and the Colorado State Patrol Family Foundation (C.S.P.F.F.).&nbsp; This Training Center Agreement identifies the CSPFF as the single source provider of the Instructor Development Course necessary for an individual to become trained to deliver the Alive at 25 N.L.E.C. course in a community.</p>
		<p>As this is a law enforcement based program, the N.L.E.C. Instructor Development Course is only available to individuals who are currently sworn law enforcement officers or to those individuals who have recently separated in good standing from their law enforcement agency.&nbsp; Additionally, individuals who are interested in becoming certified&nbsp;to instruct this program should have&nbsp;experience enforcing motor vehicle laws and&nbsp;responding to and/or investigating motor vehicle crashes.&nbsp; Experience as an instructor/trainer in any capacity as well as experience working with young adults is also&nbsp;of great benefit.</p>
		<p>This program is available nationally.&nbsp; There are, however, several states within which National Safety Council chapter reside.&nbsp; These chapters have the ultimate authority to accept or reject this program.&nbsp; Please do not hesitate to contact us&nbsp;to engage&nbsp;our assistance in helping to determine if a chapter exists in your community.&nbsp; We can be reached at
		 <script language='JavaScript' type='text/javascript'>
		 <!--
		 var prefix = '&#109;a' + 'i&#108;' + '&#116;o';
		 var path = 'hr' + 'ef' + '=';
		 var addy72091 = '&#105;nf&#111;' + '&#64;';
		 addy72091 = addy72091 + '&#97;l&#105;v&#101;&#97;t25' + '&#46;' + '&#117;s';
		 var addy_text72091 = '&#105;nf&#111;' + '&#64;' + '&#97;l&#105;v&#101;&#97;t25' + '&#46;' + '&#117;s';
		 document.write( '<a ' + path + '\'' + prefix + ':' + addy72091 + '\'>' );
		 document.write( addy_text72091 );
		 document.write( '<\/a>' );
		 //-->\n </script><script language='JavaScript' type='text/javascript'>
		 <!--
		 document.write( '<span style=\'display: none;\'>' );
		 //-->
		 </script>This email address is being protected from spam bots, you need Javascript enabled to view it
		 <script language='JavaScript' type='text/javascript'>
		 <!--
		 document.write( '</' );
		 document.write( 'span>' );
		 //-->
		 </script> or by telephone 1-866-605-3900.
		</p>
		<p>
		We look forward to working with you and helping your community save the lives of their children.
		</p>
		</td>
	</tr>
	</table>
	<span class="article_seperator">&nbsp;</span>
</div>
</div>