<div style="text-align: center; margin-top: 18px; margin-bottom: 12px; font-style: italic; color: #aaaaaa;">
Please support our partners:
</div>
<div class="row" style="text-align: center;">
<div class="col-sm-3 col-xs-6">
<a href="http://www.cspff.net/" target="_blank" class="noDots" <?php echo $this->tracker->insertTracker('CSPF_org') ?>>
<img src="<?php echo A25_Link::to('/templates/aliveat25/images/footerLogos/cspff.png')?>" border="0" alt="Colorado State Patrol Family Foundation" width="130" /></a>
</div>
<div class="col-sm-3 col-xs-6" style="margin: 10px 0px;">
<a href="http://www.maxxautorecovery.com/" target="_blank" class="noDots" <?php echo $this->tracker->insertTracker('Maxx') ?>>
<img src="<?php echo A25_Link::to('templates/aliveat25/images/footerLogos/maxx.png')?>" border="0" alt="Maxx Fleet Service" width="120" height="54" /></a>
</div>
<div class="clearfix visible-xs">
</div>
<div class="col-sm-3 col-xs-6" style="margin: 3px 0px;">
<a href="https://www.expresstoll.com" target="_blank" class="noDots" <?php echo $this->tracker->insertTracker('E470') ?>>
<img src="<?php echo A25_Link::to('templates/aliveat25/images/footerLogos/E470.png')?>" border="0" alt="E-470 Express Toll" width="83" height="68" /></a>
</div>
<div class="col-sm-3 col-xs-6" style="margin: 21px 0px;">
<a href="http://www.schomphonda.com/" target="_blank" class="noDots" <?php echo $this->tracker->insertTracker('SchompHonda') ?>>
<img src="<?php echo A25_Link::to('templates/aliveat25/images/footerLogos/SchompHonda.jpg')?>" border="0" alt="Ralph Schomp Honda" width="105" height="32" /></a>
</div>
<div class="clearfix visible-xs">
</div>
<div class="col-sm-4 col-xs-6" style="margin: 26px 0px;">
<a href="http://www.brandonandpaulfoundation.org/" target="_blank" class="noDots" <?php echo $this->tracker->insertTracker('BrandonPaulFoundation') ?>>
<img src="<?php echo A25_Link::to('templates/aliveat25/images/footerLogos/BrandonPaulFoundation.png')?>" border="0" alt="Brandon & Paul Foundation" width="140" height="22" /></a>
</div>
<div class="col-sm-4 col-xs-6" style="margin: 7px 0px;">
<a href="http://www.dexknows.com/business_profiles/wayne_s_towing-b582898" target="_blank" class="noDots" <?php echo $this->tracker->insertTracker('WaynesTowing') ?>>
<img src="<?php echo A25_Link::to('templates/aliveat25/images/footerLogos/WaynesTowing.png')?>" border="0" alt="Wayne's Towing" width="92" height="60" /></a>
</div>
<div class="col-sm-4 col-xs-12" style="margin: 7px 0px;">
<a href="http://nsc.org" target="_blank" class="noDots" <?php echo $this->tracker->insertTracker('NSC_org') ?>>
<img src="<?php echo A25_Link::to('images/nsc.png')?>" border="0" alt="National Safety Council" width="161" height="68" /></a>
</div>
</div>
