<?php
$mainLocation = A25_Record_Location::retrieve(ServerConfig::parentLocationId);
?>
<p>
We recommend that you register for a course through our web site, which also
allows you to make payments and transfer your course registration. All courses
close for registration <?php echo $mainLocation->enrollment_deadline ?> 
in advance.  We do not accept same day registrations or walk-up students.
Because of the high demand for our classes, we recommend you register at least
7 days in advance for a class.  Pre-registrations that do not include a payment
do not guarantee your seat in a course.
</p>
<p>
Please note that refunds are not issued for any reason. We also reserve the
right to cancel a course due to low enrollment, weather, or unforeseen
emergencies.  If your course is cancelled, you will be notified by an instructor
and have the opportunity to apply your payment to a new course date.
</p>