<h2>About the <?php echo PlatformConfig::STATE_NAME; ?> Alive at 25 program</h2>
<p>
Alive at 25 is a young driver intervention program developed by the National Safety
Council for drivers between 15 and 24 years of age. This course is being offered in
Maine by the Safety & Health Council of Northern New England, a local chapter of the
National Safety Council. This course is a 4-hour program that focuses on the decision
making processes and behaviors that young drivers and passengers display in a motor
vehicle and is designed to prevent the number one killer of teens, automobile crashes.
</p><p>
Alive at 25 is taught by driver education instructors and off-duty law enforcement
officers who hold candid conversations with students about what can happen if they
practice risky behavior or make other poor decisions in an automobile. The Safety &
Health Council of Northern New England has recently established a Maine Alive at
25 Community Coalition of various agencies and driving experts in the state to work
together on the establishment of Alive at 25 classroom programs on a state-wide basis
in Maine.
</p><p>
Driving behaviors and their implications are explored in-depth through a combination of
subject discussions and interactive teaching tools including:
<ul>
  <li>Risk identification</li>
  <li>Interactive video participation</li>
  <li>Experience sharing with peers</li>
  <li>Role-playing in various driving situations</li>
  <li>Driving law review-local traffic</li>
  <li>Graduated driver&rsquo;s license requirements</li>
</ul>
</p><p>
Alive at 25 is being offered in locations all over the state of Maine, and is approved
by the Maine Secretary of State&rsquo;s office for license re-instatement upon successful
completion of the program.
</p><p>
The Alive at 25 course is specifically designed for 15-24 year olds. If you are over 25
years old, this course will not fulfill requirements set forth by the agency referring you to
attend a Defensive Driving Course or suspended license re-instatement program.
</p><p>
We are happy to answer any questions you may have. &nbsp;<a href="<?php echo
PlatformConfig::contactUrl(); ?>">Contact Us</a>.
</p>