<ul>
  <li>Because of the high demand for our classes, we recommend you register at
least 5 days in advance for a class.  If space is available, registrations will
be accepted until 24 hours in advance.</li>
  <li>Pre-registrations that do not include a payment do not guarantee a
seat in the class.</li>
  <li>Please note that refunds are not issued for any reason.</li>
  <li>We cannot accept walk-in registrations; everyone must be pre-registered.</li>
  <li>We reserve the right to cancel courses with insufficient enrollment.
Cancellation notifications will be made within 3 days prior to the
course, and refunds will be granted in this instance.</li>
</ul>
