<style type="text/css">
h1 {
	margin-top: 20px;
    text-align: center;
    font-size: 40px;
    color: #006600;
}
h2 {
	font-size: 32px;
	color: #000066;
    text-align: center;
    margin-top: 32px;
    margin-bottom: 32px;
}
#frontpage_summary p {
		padding-left: 32px;
		padding-right: 32px;
		padding-top: 12px;
}
a.frontpage_button {
	display: flex;
	border: 1px solid black;
	padding: 12px 10px;
	width: 100%;
	text-align: center;
	text-decoration: none;
    background: <?php echo A25_DI::PlatformConfig()->colorScheme()->backgroundColor() ?> url(<?php echo ServerConfig::currentUrl() ?>/templates/aliveat25/images/calloutBG.png) repeat-x top center;
	color: white;
	font-weight: bold;
    height: 64px;
    align-items: center;
    justify-content: center;
}
a.frontpage_button:hover {
	color: black;
	background: url(<?php echo ServerConfig::currentUrl() ?>/templates/aliveat25/images/buttonOn.jpg) repeat-x center;
    background-size: 100% 100%;
}
.frontpage_image {
    padding-left: 32px;
    margin-bottom: 24px;
    max-width: 100%;
}
@media (max-width: 768px) {
  .frontpage_image {
    padding-right: 32px;
  }
}
</style>
<div id="frontpage_summary" style="
	color: black;
	border-left: 1px solid gray;
	border-right: 1px solid gray;
	border-top: 1px solid black;
	font-size: 14px;">
<h1>Colorado Safe Driver</i></h1>
<h2>Online Defensive Driving modules</h2>
<div class="row" style="margin: 5px 0px;">
  <div class="col-sm-4">
    <a class="frontpage_button" href="/component/option,com_course/task,confirm/course_id,5/Itemid,19/">
      Avoiding Fixed Objects
    </a>
  </div>
  <div class="col-sm-4">
    <a class="frontpage_button" href="/component/option,com_course/task,confirm/course_id,6/Itemid,19/">
      Avoiding Aggressive Driving
    </a>
  </div>
  <div class="col-sm-4">
    <a class="frontpage_button" href="/component/option,com_course/task,confirm/course_id,7/Itemid,19/">
      Backing and Parking Lot Strategies
    </a>
  </div>
</div>
<div class="row" style="margin: 5px 0px;">
  <div class="col-sm-4">
    <a class="frontpage_button" href="/component/option,com_course/task,confirm/course_id,8/Itemid,19/">
      Avoiding Fatigued Driving
    </a>
  </div>
  <div class="col-sm-4">
    <a class="frontpage_button" href="/component/option,com_course/task,confirm/course_id,9/Itemid,19/">
      Avoiding Impaired Driving
    </a>
  </div>
  <div class="col-sm-4">
    <a class="frontpage_button" href="/component/option,com_course/task,confirm/course_id,10/Itemid,19/">
      Intersections
    </a>
  </div>
</div>
<div class="row" style="margin: 5px 0px;">
  <div class="col-sm-4">
    <a class="frontpage_button" href="/component/option,com_course/task,confirm/course_id,11/Itemid,19/">
      Lane Management
    </a>
  </div>
  <div class="col-sm-4">
    <a class="frontpage_button" href="/component/option,com_course/task,confirm/course_id,12/Itemid,19/">
      Speed Management
    </a>
  </div>
  <div class="col-sm-4">
    <a class="frontpage_button" href="/component/option,com_course/task,confirm/course_id,13/Itemid,19/">
      Weather and Road Conditions
    </a>
  </div>
</div>
<div class="row" style="margin-top: 32px">
  <div class="col-sm-7">
    <img class="frontpage_image" src="<?php echo A25_Link::to('/PlatformTemplates/screenshot.png')?>" />
  </div>
  <div class="col-sm-5">
    <div style="max-width: 240px; border: 1px solid #FFFFBB; padding: 2px; margin-left: 32px;">
      <div style="padding: 22px; background-color: #FFFFBB; font-size: 16px;">
        <div style="margin-bottom: 12px; color: #000077; font-size: 20px;">Only <b>$<?php echo PlatformConfig::defaultCourtFee?></b><br/> per module</div>
        <div style="margin-bottom: 24px;">Learn at your own pace, from the comfort of your own home. Select a course above to enroll.</div>
      </div>
    </div>
  </div>
</div>
<p>
<i><?php echo PlatformConfig::courseTitleFull; ?></i> are online courses based on the same content used in
the National Safety Council instructor-led <i>Defensive Driving Course</i>
&mdash; the most widely used driver safety program in the world. Through
animation, narration, video and interactive exercises the online defensive
driving course offers an engaging, interactive learning environment where
students analyze real driving situations, spot driving hazards, and identify the
correct defenses.
</p>
<h2>What you will learn</h3>
<ul style="margin-left: 12px;">
<li>Defensive driving strategies and techniques to reduce the chance of collision</li>
<li>How drugs, alcohol, physical conditions and emotions affect driving decisions</li>
<li>How to deal with driver distractions and fatigue</li>
<li>Physical forces of a collision</li>
<li>The importance of occupant safety devices and how to use them correctly</li>
</ul>
</div>
