<h2>About the <?php echo PlatformConfig::STATE_NAME; ?> Alive at 25 program</h2>
<p>
We are pleased to collaborate with law enforcement agencies who have dedicated
themselves to reducing automobile crashes involving young drivers and passengers.
</p>
<h3>Support Alive at 25 in <?php echo PlatformConfig::STATE_NAME; ?></h3>
Your financial and in-kind support can help catapult our program into the
formidable effort it needs to be.
<p>
As an Internal Revenue Service designated 501(c)3 organization, all donations
made to the <?php echo PlatformConfig::agency; ?> are tax deductible.
</p>
<p>
<strong>Please make your contributions payable to:</strong><br />
NDSC - AA25 - DDC (North Dakota Safety Council - AA25 - Defensive Driving
Courses).
</p>
<p>
<strong>Donations may be mailed to:</strong><br />
<?php echo PlatformConfig::administrativeAddressHtml(); ?>
</p>
<p>
We are happy to answer any questions you may have. Please do not hesitate to
contact us through the U.S. Mail at the above address, or stop by our office.
</p>
<p>We may also be reached by phone at <?php echo PlatformConfig::phoneNumber; ?>
&nbsp;or by facsimile at <?php echo PlatformConfig::faxNumber; ?>.
</p>
<p>
Thank you in advance for your consideration.
</p>