<h2>About the Colorado Alive at 25 program</h2>
<p>
The Colorado Alive at 25 program is managed through a joint partnership between
the <a href="http://www.nsc.org/" target="_blank">National Safety Council</a>,
the <a href="http://csp.state.co.us/" target="_blank">Colorado State Patrol</a>
and the <a href="http://www.cspff.org/" target="_blank">Colorado State Patrol
Family Foundation</a>. In 2006, over 9,000 young people attended the Alive at 25
course in Colorado.
</p><p>
Our palate of defensive driving courses is managed by a Program Manager and a
staff of three program assistants, all of whom are employees of the Colorado
State Patrol Family Foundation.
</p><p>
The primary purpose and mission of the CSPFF has been to support the surviving
family members of fallen Colorado State Patrol Troopers. The CSPFF Board of
Trustees broadened its mission and purpose to include the management of numerous
safe-diving efforts and to promote public awareness of the needless tragedies
that plague young drivers and passengers.
</p><p>
The Colorado State Patrol Family Foundation (CSPFF) has accepted the
responsibility of expanding Alive at 25 on a national scale, and is currently
supporting the emergence of Alive at 25 programs in several states. We are
pleased to collaborate with law enforcement agencies who have dedicated
themselves to reducing automobile crashes involving young drivers and passengers.
</p>