<?php
$mainLocation = A25_Record_Location::retrieve(ServerConfig::parentLocationId);

$late_fee_string = $mainLocation->late_fee_deadline . ' hours';
?>
<p>Tuition: $89</p>
<p>Discounted Tuition: $39 -- only for students taking class to obtain a driving
	permit</p>
<h2>Payment Policies</h2>
<p>Courses designated with a
<img src="/includes/js/tmt_validator/images/required.gif" border="0" align="absmiddle" />
require payment with credit card within
<?php echo A25_DI::PlatformConfig()->kickOutAfterDeadline ?>.
For all other courses, payment is due within
<?php echo A25_DI::PlatformConfig()->kickOutBeforeDeadline ?>.</p>
<p>If payment is not received in time, your seat reservation will be lost and you will need to register again.</p>
<p>A late fee of $<?php echo $mainLocation->late_fee ?> applies to any payment
that occurs within <?php echo $late_fee_string; ?> of the course or later.
</p>
<p>A no-show fee of $<?php echo A25_DI::PlatformConfig()->noShowFee ?> for
regular tuition or $<?php echo A25_DI::PlatformConfig()->noShowDiscountedFee ?> 
for discounted tuition will be charged if you register but do not show up for a class.</p>
<p>All payments are NON-REFUNDABLE and cannot be transferred to any other student account.</p>

<p>No payments are accepted at the class location.</p>

<h2>Payment Options</h2>

<p>Pay your tuition with a credit/debit card online or by calling
<?php echo PlatformConfig::phoneNumber ?>.  (Only <?php echo A25_DI::PlatformConfig()->acceptedCards ?> accepted)</p>

<p>Or, mail a MONEY ORDER payable to <?php echo A25_DI::PlatformConfig()->paymentTo ?> to this address:</p>

<p><?php echo PlatformConfig::paymentAddressHtml() ?></p>

<p>Please include the student's name and Alive at 25 Student ID # with your
payment.  If your form of payment is not approved by your financial institution,
an additional $<?php echo $mainLocation->late_fee ?> late fee and
$<?php echo A25_DI::PlatformConfig()->nsfFee ?> NSF fee will apply.</p>
