<h1>Support Safe Driving Among Teens - ALIVE AT 25</h1>
<p>
We are in the midst of undertaking one of the most important efforts in our
nation today as we endeavor to create a seamless network of law enforcement
agencies across the country who are committed to the proposition that most
young-driver and passenger deaths are preventable. More than 10,000 of our
children and young adults will be killed in an automobile this year and we need
your help.
</p><p>
Your financial and in-kind support can help catapult our program into the
formidable effort it needs to be.
</p><p>
As an Internal Revenue Service designated 501(c)3 organization, all donations
made to the Colorado State Patrol Family Foundation are tax deductible.
</p><p>
<b>Please make your contributions payable to:</b><br/>
CSPFF &ndash; DDC (Colorado State Patrol Family Foundation &ndash; Defensive
Driving Courses).
</p><p>
<b>Donations may be mailed to:</b><br/>
CSPFF &ndash; DDC<br/>
55 Wadsworth Blvd<br/>
Lakewood, CO 80226-1501.
</p><p>
We are happy to answer any questions you may have. Please do not hesitate to
contact us through the U.S. Mail at the above address, or at our office located
at 55 Wadsworth Boulevard, Lakewood, CO.
</p><p>
We may also be reached by phone <?php echo PlatformConfig::phoneNumber ?> or by
facsimile <?php echo PlatformConfig::faxNumber ?>.
</p><p>
Thank you in advance for your consideration.
</p>
