<p>
California Safe Driver stands by and supports the National Safety
Council's (NSC) Diversity, equity and inclusion (DE&I) policy that states, "At
NSC, we demonstrate our commitment to diversity, equity and inclusion through
our culture and our values. Our culture embraces all people regardless of
ancestry, color, national origin, race, gender identity, sex, sexual
orientation, age, religion, physical or mental disability, or veteran status. We
boldly empower our team to model respect and dignity. We find impactful
opportunities for growth and development. We create a safe environment that
includes mental, physical, psychological, and emotional protections. To be NSC
is to deliver our mission by working together - our employees, members, and
stakeholders - in such a way that everyone feels a sense of belonging.
</p><p>
We believe that you can't be safe if you don't feel safe. Feeling safe requires
a commitment to equitable policy implementation and promoting diversity in the
safety profession. We must cultivate our own diverse, inclusive, and equitable
work environment to deliver on our mission to save lives, from the workplace to
anyplace."
</p><p>
*California Safe Driver and the NSC is an equal opportunity employer.
</p>