<div style="text-align: center; margin-top: 18px; margin-bottom: 12px; font-style: italic; color: #aaaaaa;">
Cobert Safety Professionals LLC, DBA California Safe Driver<br/>
A safety partner with the National Safety Council
</div>
<div class="row" style="text-align: center;">
    <div class="col-sm-5 col-xs-12" style="margin: 7px 0px;">
        <a href="http://www.californiasafedriver.com" target="_blank" class="noDots">
        <img src="<?php echo A25_Link::to('images/CASafeDriver.png')?>"
        border="0" alt="California Safe Driver" width="84" height="84" /></a>
    </div>
    <div class="col-sm-7 col-xs-12" style="margin: 7px 0px;">
        <a href="http://nsc.org" target="_blank" class="noDots" <?php echo $this->tracker->insertTracker('NSC_org') ?>>
        <img src="<?php echo A25_Link::to('images/nsc.png')?>"
        border="0" alt="National Safety Council" width="161" height="68" /></a>
    </div>
</div>
