<style type="text/css">
    .reg {
        font-size: 9px;
    }
</style>
<p>Alive at 25<span class='reg'>&reg;</span> is a 4.5-hour, highly interactive
National Safety Council Defensive Driving Course instructed live via Zoom. It
focuses on young adult drivers aged 16-24, the group with the highest risk of
death in motor vehicle crashes. Alive at 25<span class='reg'>&reg;</span>
incorporates the Kahoot learning platform, and is designed to engage
participants in learning defensive driving skills, making sound driving choices,
and understanding the consequences of poor driving conduct. In the class,
students learn about common California vehicle code violations, DUI, and commit
to being a safer driver.
</p><p>
Alive at 25<span class='reg'>&reg;</span> incorporates Reality Therapy and
Choice&#8482; Theory techniques to help participants identify the five basic
needs that drive human behavior: survival, love and belonging, fun, freedom, and
power.
</p><p>
Driver education teaches the mechanics of car and road handling and state law,
but Alive at 25<span class='reg'>&reg;</span> focuses on inexperience,
distractions, poor judgment, peer pressure, a tendency to underestimate risk,
decision-making, and consequences. This driver safety course provides tools for
making positive choices in a way teens and young adults can relate to. With a
strong emphasis on classroom interaction, students are encouraged to join
nonthreatening, nonjudgmental discussions, exploring how changing driving
behavior makes personal, legal, and financial sense.
</p><p>    
<b>Course objectives</b><br/>
<ul>
<li>Recognize that drivers in the 15-24 age group are more likely than anyone else
to be injured or killed in a vehicle crash and understanding why those drivers
are at such high risk</li>
<li>Understand the consequences of making poor judgments or taking unnecessary risks in a vehicle</li>
<li>Recognize the positive characteristics that can help them and their friends make wise driving decisions</li>
<li>Identify actions they can take to keep control whether they are a driver or a passenger</li>
<li>Commit to making better driving choices and to help their friends make better driving choices</li>
</ul>
<h2>"Other programs may teach the class, we facilitate the learning."</h2>
<p>
California Safe Driver has been a proud member of the National Safety
Council, providing California with the Alive At 25 & ADoD Programs since 2009.
Since then we have trained thousands of students to be safer, more responsible
drivers. In post course anonymous surveys, our students overwhelmingly report
that they will be safer drivers because of their course, and would recommend the
course to other people in their age group.
</p>
<p>Beginning February of 2024, we will be conducting a pilot program utilizing
the virtual classroom for live, Alive at 25 and ADoD / Attitudinal Dynamics of
Driving Courses. A major advantage for our students is the accessibility factor,
especially for those students who may not be licensed, or have had their
licenses restricted and/or suspended. This will also help in providing students
access to courses who live outside of the areas where classes are typically
offered, while saving some of our students time and money.
</p>
<p>After much research on how best to implement an effective and interactive
curriculum utilizing a cognitive behavioral based foundation, we have chosen the
Kahoot Program.
</p>
<p>
<i>Evidence shows that impactful learning includes social, emotional, and
academic integration.</i> That's why we facilitate curriculums utilizing an
interactive, cognitive behavior therapy based approach to learning.
</p>
<p>
<i>How do we know what works?</i> We find the best law enforcement experienced
facilitators, teach them how to use cognitive behavioral therapy strategies, and
create a highly interactive classroom community. Students become active
learners, and facilitators check learning throughout the class. Our well trained
and highly experienced facilitators are highly sensitive to the students'
learning process, and care deeply about their success. Additionally, we check
students' knowledge at the end of each course and engage them in anonymous
course evaluations.
</p>
<p>
<b><u>LEARNING THEORY</u></b><br/>
Kahoot! draws upon ideas from the Self-Determination Theory (SDT) of motivation,
developed by Richard Ryan, PhD and Edward Deci, PhD. SDT which posesses that
there are two different types of motivation, extrinsic and intrinsic (Rogat et
al., 2013, p. 257). Intrinsic motivation takes place when an individual engages
in an activity because they find it truly enjoyable, whereas extrinsic
motivation takes place when an individual engages in an activity to achieve an
outcome (for example to receive a reward, good grades, money, etc.) (Rogat et
al., 2013, p. 257). Kahoot! incorporates both types of motivation in its design.
Its game face interface, music, and colors makes learning fun and engaging, so
learners genuinely find it enjoyable (intrinsic motivation). Its gameshow
framework, point system, and leaderboard display promotes competition and the
desire to win in learners (extrinsic motivation).
</p>
<p>
<b><u>REFERENCES</u></b><br/>
Goel, S. (2021). This student-professor duo's $5.7 billion tech start-up is
being used in 9 million classes globally. <a href="https://www.cnbc.com/2021/11/02/kahoot-how-a-student-professor-duo-launched-a-5point7-billion-tech-idea.html">make it.</a><br/>
If you would like to read more about the successes of Kahoot! Then please follow
<a href="https://kahoot.com/research-articles/">this link</a>.
</p>
