<h2>About the <?php echo PlatformConfig::STATE_NAME; ?> Alive at 25 program</h2>
<p>
The Kentucky Alive at 25 Program is managed through Kentucky Safe Driver (KSD) a
non-profit 501 (c)3 organization established by the Colorado State Patrol Family
Foundation (CSPFF) in 2016 and is dedicated to the mission of reducing injury
and fatal crashes by providing the motoring public with defensive driving
programs and public awareness efforts throughout Kentucky.
</p><p>
Colorado State Patrol Family Foundation's (CSPFF) Defensive Driving Program has
been teaching Alive at 25 since its inception by the National Safety Council in
1994.  In 2004, the CSPFF became a National Safety Council Training Center and
Distributor, providing instructor development training in 12 different
states.  Currently, the CSPFF serves as the training center for four statewide
programs in CO, WY, ID and KY. Additionally, the CSPFF is the training
center for regional programs in CA, TX and NM.
</p><p>
All KSD programs utilize multi-agency law enforcement teams of current and
retired state, county and municipal police officers who are committed
professionals dedicated to saving lives on our roadways.
</p>