<div class="row" style="text-align: center;">
<div class="col-sm-6 col-xs-12">
<a href="http://www.cspff.net/" target="_blank" class="noDots" <?php echo $this->tracker->insertTracker('CSPF_org') ?>>
<img src="<?php echo A25_Link::to('/templates/aliveat25/images/footerLogos/cspff.png')?>" border="0" alt="Colorado State Patrol Family Foundation" width="130" /></a>
</div>
<div class="col-sm-6 col-xs-12" style="margin: 7px 0px;">
<a href="http://nsc.org" target="_blank" class="noDots" <?php echo $this->tracker->insertTracker('NSC_org') ?>>
<img src="<?php echo A25_Link::to('images/nsc.png')?>" border="0" alt="National Safety Council" width="161" height="68" /></a>
</div>
</div>
