<style>
    #faq {
        font-weight: bold;
        padding: 0px 40px;
        text-align: left;
        font-size: 14px;
    }
    #faq > li {
        padding-top: 14px;
    }
    #faq > li > ul {
        font-weight: normal;
        font-size: 12px;
    }
    #highlight {
        background-color: #d9ead3;
    }
</style>
<div class="shell">
<div class="colHeader" style='text-align: center;'><?php echo A25_DI::PlatformConfig()->contactUsTitle; ?></div>
<div align="center">
    <h1 style="color: #38761d; text-decoration: underline; font-size: 20px;">Answers to Common Questions</h1>
    <p style="font-weight: bold; font-size: 14px;">We do not issue refunds for any reason.</p>
    <ul id="faq">
        <li>I did not receive my <span id="highlight">student workbook</span>. When will it arrive?
            <ul>
                <li>We will mail you your student workbook 2 weeks before your class date, not from the time of your course registration.</li>
                <li>Do you have a shared or community mailbox?
                    <ul>
                        <li>Please check with the people you share your mailbox with.</li>
                    </ul>
                </li>
                <li>Do you live in an apartment building? Did you include your apartment number when you registered? Do you have a small mailbox?
                    <ul>
                        <li>Check with your building manager. The delivery person may have left the package out in the community space.</li>
                        <li>Email us if you need to update your address. Change of mailing address for your student workbook must be made 15 days (or more) prior to the class date. Once a booklet is mailed to the address on file, any additional shipped book will result in a $30 replacement fee.</li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
    <p style="font-weight: bold; font-style: italic;">Email us if <span id="highlight">your class is within the next 5 days</span> and you don't have your workbook.</p>
    <ul id="faq">
        <li><span id="highlight">I don't have</span> a desktop computer, laptop computer, or tablet.
            <ul>
                <li>You are required to use a computer or tablet to participate in the Alive at 25 &amp; ADoD Classes.
                    <ul>
                        <li>Can you borrow a computer or tablet from a friend or family member? Can you use a school or work computer?</li>
                    </ul>
                </li>
            </ul>
        </li>
        <li>I didn't receive my <span id="highlight">Zoom login</span> information.
            <ul>
                <li>This information is emailed to students both 1 week <i>and</i> 1 hour before class.
                    <ul>
                        <li>Check that you provided us with your correct email address.</li>
                        <li>Check your SPAM folder.</li>
                    </ul>
                </li>
            </ul>
        </li>
        <li>I don't have a <span id="highlight">Zoom account</span>.
            <ul>
                <li>You do not need a Zoom account to join a Zoom meeting. If someone invites you to their meeting, you can participate without creating or signing in to an account. Simply click on the link emailed to you. However, a Zoom account allows you to update personal settings to get the most out of your Zoom virtual class experience. It is free and easy to do.
                    <ul>
                        <li>You can create a free Zoom account by following this link: <a href="https://zoom.us/signup#/signup" target="_blank">https://zoom.us/signup#/signup</a>.</li>
                    </ul>
                </li>
            </ul>
        </li>
        <li><span id="highlight">Why wouldn't my teacher</span> let me take the class or finish it?
            <ul>
                <li>According to the rules and expectations included in your registration and emailed to you as a reminder, students must check in to their classes 45 minutes before the start time, have their workbook and government ID, and have a computer or tablet. Students must attend the entire class and not lose internet service for more than five minutes.</li>
            </ul>
        </li>
        <li>What if <span id="highlight">I was late</span> for my course?
            <ul>
                <li>Late students are not admitted to classes. There are no refunds for missed classes.</li>
                <li>Students are required to check into their class 45 minutes before the start time to allow time for all students to check in and for you to complete a pre-class assignment provided at that time.
                    <ul>
                        <li>Students who are late and not admitted will need to register for a new course and pay again. There are no refunds for late students.
                            <ul>
                                <li>The above listed information was provided to you at the time of registration and emailed to you.</li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
        <li><span id="highlight">I didn't attend</span> my course. How do I re-register for a new course?
            <ul>
                <li>Please log in to your account and go to find a course. Select "Enroll" for the course you would like to take. There are no refunds for missed classes.
                    <ul>
                        <li style="font-weight: bold; font-style: italic;">You must use your existing account to sign up for a new class (same username and password).</li>
                    </ul>
                </li>
            </ul>
        </li>
        <li>How do I <span id="highlight">change or transfer</span> my registration to a different course?
            <ul>
                <li>If you <b>already registered</b> for a course and want to transfer to a different one, log in to your account and go to "Enrollments," where you can view all past and current registrations.
                    <ul>
                        <li>You can cancel an upcoming enrollment up to 30 days before the start of the class and will then be able to register for a new class. Your payment will transfer to your new class as long as the new class is within one year of the payment date.</li>
                        <li><b>Have you already received your student workbook?</b> You can add a class yourself up to 14 days before the new start date. If the class is within 14 days, you can email us to see if there is room in it.</li>
                    </ul>
                </li>
            </ul>
        </li>
        <li>How do I get a <span id="highlight">replacement certificate</span> of completion for my course?
            <ul>
                <li>Please email us at <a href="mailto:info@californiasafedriver.com" target="_blank">info@CaliforniaSafeDriver.com</a>.
                    <ul>
                        <li>There is a fee for replacement certificates, and you should allow approximately two weeks for processing and delivery.</li>
                        <li>In accordance with the rules of the National Safety Council, we are not allowed to send certificates electronically.</li>
                        <li>Why is there a fee to replace my certificate?
                            <ul>
                                <li>The National Safety Council provides one certificate per book. If we replace your certificate, we must purchase a new book set for you and pay for shipping and handling.</li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
        <li>How do I update my <span id="highlight">personal information</span>?
            <ul>
                <li><a href="mailto:info@californiasafedriver.com" target="_blank">Email us</a> from the same email account you registered with. Include your name, date of birth, the course you registered for, and the changes you request. Please allow at least one full business day for a response.</li>
            </ul>
        </li>
        <li>I've forgotten my <span id="highlight">username and password</span>. Help!
            <ul>
                <li>Please <a href="mailto:info@californiasafedriver.com" target="_blank">email us</a> using the email account you registered with. Include your name and date of birth, and we will email you your username and password.</li>
            </ul>
        </li>
        <li>How do I make a <span id="highlight">payment</span> online?
            <ul>
                <li>Log in to your account and go to "Payments." This page displays past payments, available credits to apply to a course, and the option to pay online with a credit or debit card.</li>
            </ul>
        </li>
    </ul>
<div id="colContent">

<h2><?php echo PlatformConfig::agency ?></h2>
<?php echo PlatformConfig::contactUs() ?>

<span class="article_seperator">&nbsp;</span>
</div></div></div>
