
<div class="locationContent">
<div class="colHeader">Privacy Policy</div>
<img src="/images/headers/12.jpg" style="width: 100%;" />
<div id="colContent" style="min-height: 0px;">
<?php echo PlatformConfig::agency ?> - Privacy Policy<span class="bodyText"><strong><br />
</strong><span style="font-style: italic">Last Modified: February 9, 2010 </span></span><br />
<br />
We care
about your privacy. This policy describes what information we collect
and how we use it. <br />
<br />
<span style="font-weight: bold" class="h5">Website Data</span><br />
When you browse through our site, we collect information on the
efficiency and working of our Web site. This information includes your
IP address, the number of times a web page is accessed, the browser
used, referring web sites, and paths taken through the website, and search terms entered to
find our site. We keep this information for an indefinite time to
improve the operation of our site and serve users better.<br />
<br />
<span style="font-weight: bold">Contact Information</span><br />
Our visitors may voluntarily send us information through use of our
online forms. These forms facilitate communication between us
and visitors of our Web site. Our intentions are always clearly
identified and we will not share or sell your personal information to
any third parties for any reason, unless required by law.
<br />
<span style="font-weight: bold"><br />
Email Policy</span><br />
We are vehemently against spam. We will not send you any
unsolicited email unless you have joined our mailing list or given us
prior written or verbal consent. If you have already joined our mailing
list and would like to be removed, simply follow the &quot;unsubscribe&quot; link
at the bottom of any email.
<br />
<strong><br />
Cookies</strong><br />
A cookie is nothing more than a small text file that resides on your
hard drive.  We only use cookies to track a client&#39;s login
status when accessing our password protected client directory.
<br />
<strong><br />
Links</strong><br />
We link to a number of other Web sites on the Internet. If
you choose to follow a link, we recommend that you stay current with
the privacy policies of that Web site as we cannot be held responsible
with how they manage information about their users. <br />
<span class="bodyText"><strong><br />
Policy Changes</strong></span><br />
<span class="bodyText">
Any changes to this Privacy Policy will be posted on this page so that
you are always aware of the information that we collect, how we use it,
and under what circumstances we disclose it.</span>
</div>
</div>