<p>
Why the National Safety Council's Alive at 25 and Attitudinal Dynamics of Driving Courses?
</p><p>
The National Safety Council is the only safety organization to be chartered by
Congress and recognized for its leadership in safety programs and advocacy. In
1964, the Council pioneered the country's first Defensive Driving Course. Since
then, we have trained more than 80 million drivers in all 50 states - and around
the world.
</p>