<div style="text-align: center; margin-top: 18px; margin-bottom: 12px; font-style: italic; color: #aaaaaa;">
Please support our partners:
</div>
<div class="row" style="text-align: center;">
<div class="col-sm-7 col-xs-12" style="margin: 7px 0px;">
<a href="http://www.survivalcpr.com/" target="_blank" class="noDots"
<?php echo $this->tracker->insertTracker('SurvivalCPR') ?>>
<img src="<?php echo A25_Link::to('templates/aliveat25/images/footerLogos/survival.png')?>"
border="0" alt="Survival CPR" width="305" height="100" /></a>
</div>
<div class="col-sm-5 col-xs-12" style="margin: 7px 0px;">
<a href="http://cobertsafetyprofessionals.com" target="_blank" class="noDots" style="color: #fe4900"
<?php echo $this->tracker->insertTracker('cobert') ?>>
<img src="<?php echo A25_Link::to('images/cobert.png')?>"
border="0" alt="Cobert Safety Professionals" width="200" height="84" /></a>
</div>
</div>
