<p><b>A</b>ttitudinal <b>D</b>ynamics <b>o</b>f <b>D</b>riving, (ADoD) is a
highly interactive 8-hour behavior-based course instructed live on Zoom and 
incorporates the Kahoot learning platform. It demonstrates the direct connection
between attitude and choice and the potential results of poor driving conduct.
</p><p>
ADoD is an 8-hour diversion program designed to help participants make a direct
connection between their attitude and their choice to make poor decisions. They
will learn how to take responsibility for their actions, and see how the choices
they make have financial, legal, and personal consequences. The course guides
participants to ask questions, share opinions and join in non-threatening,
non-judgmental discussions. Attitudinal Dynamics of Driving is used extensively
for court referrals, and also as a diversion program for people with DUI
violations, excessive points, or any violation of law including minor alcohol
violations.
</p><p>
The 8-hour National Safety Council's ADoD Course is based on the work of behaviorist Dr. William Glaser and his
book, <u><i>Choice Theory</i></u>. Participants come to better understand what
motivates their driving behaviors and make better driving choices. <i>The course
includes a self-assessment profile and personal action plan to change their
driving behavior.</i>
</p>
<p>
According the National Safety Council, in a study done in 2015,
</p>
<ul>
<li>In 1994, Massachusetts began using the Attitudinal Dynamics of Driving
Course for the retraining of repeat traffic offenders. By 2014, more than
631,500 had completed the course. Periodic studies are conducted (2010 & 2015
included) to measure and document the effectiveness of the course.</li>
<li>The most recent study as of 2015 shows that "ADoD" graduates in
Massachusetts had the following reduction in traffic violations:</li>
<ul>
<li><b>Minor traffic violations decreased an average of 80%</b></li>
<li><b>Major traffic violations decreased an average of 77%</b></li>
<ul>
<li>For the 12 months following DDC-"ADoD" participation (except for females 65
years and older who had an insufficient sample to test)</li>
</ul>
</ul>
</ul>
<p>
These National Safety Council Defensive Driving Courses are not recognized by
the California Department of Motor Vehicles as traffic school and are not
considered point reduction courses. They may or may not be recognized by some
California insurance companies for premium discounts.  Please check with your
individual insurance provider for information.
</p>
