<style type="text/css" media="screen">
	#pgsContainer {
		padding: 0px;
		margin-left: auto;
		margin-right: auto;
		width: 778px;
		background: #abedfb;
		border-left: 1px solid #fff;
		border-right: 1px solid #fff;
		border-top: 1px solid #fff;
		font-size: 12px;
		line-height: 17px;
		font-family: Verdana, Geneva, Arial, SansSerif, Helvetica;
		color: #000;
	}
		
	#pgsHead {
		margin: 0px;
		text-align: center;
	}

	#pgsContent {
		padding: 10px 0px 10px 10px;
		text-align: left;
	}
	
	#pgsTitle {
		float: left;
		width: 502px;
		padding: 0px 0px;
	}

	#pgsLeftCol {
		float: left;
		width: 502px;
	}

	.pgsTitleCell {
		font-size: 22px;
		line-height: 24px;
		font-weight: bold;
		padding: 0px 10px;
	}

	.pgsCell {
		width: 231px;
		padding: 0px 10px;
		vertical-align: top;
	}

	#pgsLeftCol ul {
		padding-left: 10px;
		*padding-left: 0px;
		*margin-left: 6px;
		font-weight: bold;
	}

	#pgsLeftCol li {
		padding-bottom: 10px;
	}

	#pgsRightCol {
		float: left;
		width: 266px;
	}
</style>
<div id="pgsContainer">
	<div id="pgsHead">
		<a href="http://www.parentalguidancesystems.com/" target="_blank"><img src="images/pgsHead.jpg" border="0" /></a>
	</div>
	<div id="pgsContent">
		<div id="pgsLeftCol">
			<table cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td colspan="2" class="pgsTitleCell">
						Easy, Effective & Affordable
					</td>
				</tr>
				<tr>
					<td class="pgsCell">
						<p>
						With fast cars, peer pressure, and limited driving experience, teens and cars are a potentially dangerous mix. 
						</p><p>
						The <b>Parental Guidance System</b> can help you supervise your teen's driving. Using the latest GPS-tracking technology, the system delivers critical, up-to-the- minute information via your cell phone, e-mail, or web-browser.
						</p><p>
						You'll know where and how fast your teen drives and whether your teen travels outside of an allowed area.
						</p>
					</td>
					<td class="pgsCell">
						<ul>
						<li>View the location of your teen's vehicle on a web-based map</li>
						<li>Monitor speeding violations</li>
						<li>Monitor travelling outside of areas you designate as allowed</li>
						<li>Receive 24/7 alerts by e-mail and cell phone</li>
						<li>Go online to configure your notifications, get vehicle reports, and manage multiple vehicles</li>
						</ul>
					</td>
				</tr>
			</table>
		</div>
		<div id="pgsRightCol">
			<a href="http://www.parentalguidancesystems.com/" target="_blank"><img src="images/pgsCallout.jpg" border="0" /></a>
		</div>	
		<br clear="all" />
	</div>
	<br clear="all" />
</div>