<style type="text/css">
h1{
	padding-left: 32px;
	margin-bottom: 20px;
	margin-top: 20px;
}
</style>
<div id="frontpage_summary" style="
	color: black;
	border-left: 1px solid gray;
	border-right: 1px solid gray;
	border-top: 1px solid black;
	font-size: 14px;">
<h1>The DDC Online Motorcycle Safety Program is no longer available.  Please
    contact the court that referred you for a different option.</h1>
</div>