<?php 
    $tooltip = new A25_Include_Tooltip();
    $tooltip->load();
?>
<style type="text/css">
h1 {
	margin-top: 20px;
    text-align: center;
    font-size: 40px;
    color: #006600;
}
h2 {
	font-size: 24px;
    text-align: center;
    margin-top: 32px;
    text-decoration: underline;
}
#frontpage_summary p {
		padding-left: 32px;
		padding-right: 32px;
		padding-top: 12px;
}
a.frontpage_button {
	display: inline-block;
	border: 1px solid black;
	padding: 12px 10px;
	width: 100%;
	text-align: center;
	text-decoration: none;
    background: <?php echo A25_DI::PlatformConfig()->colorScheme()->backgroundColor() ?> url(<?php echo ServerConfig::currentUrl() ?>/templates/aliveat25/images/calloutBG.png) repeat-x top center;
	color: white;
	font-weight: bold;
}
a.frontpage_button:hover {
	color: black;
	background: url(<?php echo ServerConfig::currentUrl() ?>/templates/aliveat25/images/buttonOn.jpg) repeat-x center;
    background-size: 100% 100%;
}
.frontpage_image {
    display: block;
    padding: 32px;
    margin-left: auto;
    margin-right: auto;
    max-width: 100%;
}
.reg {
    font-size: 9px;
}
</style>
<div id="frontpage_summary" style="
	color: black;
	border-left: 1px solid gray;
	border-right: 1px solid gray;
	border-top: 1px solid black;
	font-size: 14px;">
<div itemscope itemtype="https://schema.org/WebSite">
    <meta itemprop="url" content="https://www.californiasafedriver.com/"/>
    <meta itemprop="name" content="California Safe Driver"/>
</div>
<h1>California Safe Driver</h1>
<p style='text-align: center;'>
Ofrecemos dos clases en espa&ntilde;ol. Alive at 25<span class='reg' style='font-size: 10px;'>&reg;</span>*
es una clase en vivo, dirigida por un instructor, interactiva por Zoom para
estudiantes menores de 25 a&ntilde;os. DDC-4 es un curso en l&iacute;nea, a su
propio ritmo. Si no est&aacute; seguro de qu&eacute; curso necesita tomar,
consulte con el tribunal que lo remiti&oacute;.
</p>
<div class="row" style="margin: 5px 0px;">
  <div class="col-sm-6">
    <a class="frontpage_button" href="https://aliveat25.us/ca/find-a-course-espanol/">
      Espa&ntilde;ol Alive at 25<span class='reg'>&reg;</span>
    </a>
  </div>
  <div class="col-sm-6">
    <a class="frontpage_button" href="https://ddconline.californiasafedriver.com/espanolDDC4">
        Espa&ntilde;ol DDC-4
    </a>
  </div>
</div>
<p>
En California Safe Driver, creemos que cuando se trata de conducci&oacute;n
segura, la educaci&oacute;n y la concienciaci&oacute;n salvan vidas. Por eso
nuestros profesionales de seguridad p&uacute;blica altamente capacitados
imparten el Curso de Conducci&oacute;n Defensiva del National Safety Council,
<b>Alive at 25<span class='reg' style='font-size: 18px;'>&reg;</span></b>.
</p>
<h2>&iquest;Por qu&eacute; es tan efectivo nuestro aprendizaje en l&iacute;nea?</h2>
<p>
Despu&eacute;s de mucha investigaci&oacute;n sobre la mejor manera de apoyar un
curr&iacute;culo eficaz e interactivo para respaldar nuestros cursos basados en
la terapia cognitivo-conductual, hemos elegido incorporar el Programa Kahoot!.
</p>
<p>
La evidencia muestra que un aprendizaje impactante incluye la integraci&oacute;n
social, emocional y acad&eacute;mica. Por eso facilitamos curr&iacute;culos que
utilizan un enfoque interactivo basado en la terapia cognitivo-conductual para
el aprendizaje. &iexcl;Y tambi&eacute;n los hacemos divertidos!
</p>
<h2>&iquest;C&oacute;mo sabemos qu&eacute; funciona?</h2>
<p>
Utilizamos a los facilitadores con la mejor experiencia en aplicaci&oacute;n de
la ley, capacitados por el National Safety Council, les ense&ntilde;amos
c&oacute;mo usar estrategias de terapia cognitivo-conductual y creamos una
comunidad de aula altamente interactiva. Los estudiantes se convierten en
aprendices activos y los facilitadores verifican el aprendizaje a lo largo de la
clase. Nuestros facilitadores, bien entrenados y experimentados, son sensibles
al proceso de aprendizaje de los estudiantes y se preocupan profundamente por su
&eacute;xito. Adem&aacute;s, al concluir cada curso, verificamos el conocimiento
de los estudiantes y los involucramos en evaluaciones an&oacute;nimas y abiertas
del curso. Estas evaluaciones se utilizan para monitorear continuamente el
&eacute;xito de los cursos en ayudar a los estudiantes a identificar y cambiar
sus comportamientos; as&iacute; como para revelar cualquier &aacute;rea en la
que podamos necesitar mejorar.
</p>
<p style="text-align: center; color: #000066; font-size: 24px;">
Otros programas pueden ense&ntilde;ar la clase, nosotros facilitamos el aprendizaje.
</p>
<h2>TEOR&Iacute;A DEL APRENDIZAJE:</h2>
<p>
Kahoot! se basa en ideas de la Teor&iacute;a de la Autodeterminaci&oacute;n
(SDT) de la motivaci&oacute;n, desarrollada por Richard Ryan, PhD y Edward Deci,
PhD. La SDT afirma que existen dos tipos diferentes de motivaci&oacute;n:
extr&iacute;nseca e intr&iacute;nseca. La motivaci&oacute;n intr&iacute;nseca
ocurre cuando un individuo participa en una actividad porque la encuentra
realmente agradable, mientras que la motivaci&oacute;n extr&iacute;nseca ocurre
cuando un individuo participa en una actividad para lograr un resultado (por
ejemplo, recibir una recompensa, buenas calificaciones, dinero, etc.). Kahoot!
incorpora ambos tipos de motivaci&oacute;n en su dise&ntilde;o. Si desea leer
m&aacute;s sobre los &eacute;xitos de Kahoot!, por favor siga
<a href="https://kahoot.com/research-articles/">este enlace</a>.
</p>
<h2>Qu&eacute; aprender&aacute;n los participantes en Alive at 25<span class='reg'>&reg;</span></h2>
<p>
Alive at 25<span class='reg'>&reg;</span> incorpora t&eacute;cnicas de Terapia
de la Realidad y la Teor&iacute;a de la Elecci&oacute;n&trade; para ayudar a los
participantes a identificar las cinco necesidades b&aacute;sicas que impulsan el
comportamiento humano: supervivencia, amor y pertenencia, diversi&oacute;n,
libertad y poder.
</p>
<p>
Mientras que la educaci&oacute;n para conductores ense&ntilde;a la
mec&aacute;nica de manejar un autom&oacute;vil y el tr&aacute;fico, as&iacute;
como la ley estatal, Alive at 25<span class='reg'>&reg;</span> se centra en la
inexperiencia, las distracciones, el mal juicio, la presi&oacute;n de los
compa&ntilde;eros, la tendencia a subestimar los riesgos, la toma de decisiones
y las consecuencias. Este curso de seguridad para conductores proporciona
herramientas para tomar decisiones positivas de una manera con la que los
adolescentes pueden identificarse.
</p>
<h2>DDC-4 Online (Curso de conducci&oacute;n defensiva de 4 horas)</h2>
<p>
Este es un curso altamente atractivo que cuenta con contenido modernizado, un
aspecto y sensaci&oacute;n de &uacute;ltima generaci&oacute;n, y es muy
interactivo. El curso fue desarrollado para ser simple y directo, de modo que
cada usuario pueda comprender todos los conceptos que salvan vidas. El curso
presenta situaciones de conducci&oacute;n reales, escenarios de reconocimiento
de peligros y t&eacute;cnicas de conducci&oacute;n defensiva para motivar a los
conductores a cambiar h&aacute;bitos y comportamientos de conducci&oacute;n
riesgosos, con el fin de evitar colisiones e infracciones de tr&aacute;fico. El
curso cuenta con un plan de estudios adaptativo, personalizado seg&uacute;n el
perfil del participante, incluyendo edad, g&eacute;nero, comportamientos y
actitudes de conducci&oacute;n, veh&iacute;culo y ubicaci&oacute;n
geogr&aacute;fica, basado en una serie de respuestas a preguntas formuladas a lo
largo del curso.
</p>
<h2 style="color: <?php echo A25_DI::PlatformConfig()->colorScheme()->backgroundColor() ?>">
Certificado de Finalizaci&oacute;n
</h2>
<p>
Los estudiantes de <b>Alive at 25<span class='reg'>&reg;</span></b>
recibir&aacute;n por correo su certificado de finalizaci&oacute;n despu&eacute;s
de completar su curso. <b>Permita un m&iacute;nimo de dos semanas entre su clase
y la fecha de su audiencia para recibir el certificado. Usted es responsable de
presentar su certificado de finalizaci&oacute;n ante el tribunal en la fecha
indicada.</b>
</p><p>
Estudiantes que se inscriban en <b>DDC-4, es su responsabilidad imprimir su
certificado al finalizar el curso y presentarlo ante el tribunal en la fecha
establecida.</b> Si no tiene acceso a una impresora, env&iacute;enos un correo
electr&oacute;nico para recibir asistencia a <a href="mailto:<?php echo ServerConfig::adminEmailAddress;?>"><?php echo ServerConfig::adminEmailAddress;?></a> y
proporci&oacute;nenos su nombre completo, fecha de nacimiento, n&uacute;mero de
tel&eacute;fono y direcci&oacute;n. Tenga en cuenta que los certificados pueden
tardar hasta dos semanas en recibirse debido a los tiempos de procesamiento y
entrega postal.
</p>
<p style="font-size: 10px;">
* Estos cursos de conducci&oacute;n defensiva del Consejo Nacional de Seguridad
salvan vidas. Sin embargo, no son reconocidos por el Departamento de
Veh&iacute;culos Motorizados de California como escuela de tr&aacute;fico y no
se consideran cursos de reducci&oacute;n de puntos. Pueden o no ser reconocidos
por algunas compa&ntilde;&iacute;as de seguros de California para descuentos en
las primas. Por favor, consulte con su proveedor de seguros individual para
obtener informaci&oacute;n.
</p>
<h2 style="color: <?php echo A25_DI::PlatformConfig()->colorScheme()->backgroundColor() ?>">
&iquest;Olvidaste tu contrase&ntilde;a o inicio de sesi&oacute;n?
</h2>
<p>
(Tu c&oacute;digo postal deber&iacute;a ser tu contrase&ntilde;a). Si has
olvidado tu nombre de usuario y/o contrase&ntilde;a, por favor env&iacute;anos
un correo electr&oacute;nico a
<a href="mailto:<?php echo ServerConfig::adminEmailAddress;?>"><?php echo ServerConfig::adminEmailAddress;?></a>
y proporciona lo siguiente:
<ul>
    <li>Tu nombre</li>
    <li>Fecha de nacimiento</li>
    <li>N&uacute;mero de tel&eacute;fono</li>
    <li>Nombre de la clase que necesitas completar</li>
</ul>
</p>
</div>
