<p>Tuition: Free for those voluntarily taking the course. There is a 
<b>$35 fee</b> for students who are in any legal proceeding and required
to take the course. This includes court ordered, citation dismissal,
youth diversion, etc.</p>
<h2>Payment Policies</h2>
<p>Courses designated with a
<img src="/includes/js/tmt_validator/images/required.gif" border="0" align="absmiddle" />
require immediate payment with credit card in order to enroll.</p>

<p>All payments are NON-REFUNDABLE and cannot be transferred to any other student account.</p>

<p>Payments may be brought to class but it is recommended to pay in
advance. Checks, money orders or exact cash will only be accepted at
class.</p>

<h2>Payment Options</h2>

<p>Pay your tuition with a credit/debit card online or by calling
<?php echo PlatformConfig::phoneNumber ?> (Only <?php echo A25_DI::PlatformConfig()->acceptedCards ?> 
accepted). There is a $2.50 convenience fee for each student who
registers with a credit card online.</p>
