<p>
We recommend that you register for a course through our web site.  We do not
accept same day registrations or walk-up students.
Because of the high demand for our classes, we recommend you register at least
7 days in advance for a class.
</p>
<p>
We reserve the
right to cancel a course due to low enrollment, weather, or unforeseen
emergencies.  If your course is cancelled, you will be notified by an instructor
and have the opportunity to apply your payment to a new course date.
</p>