<p style="padding: 12px; text-align: center;">
<a href="https://cad.chp.ca.gov/"
   style="background: none;">
    <img src="<?php echo A25_Link::to('images/CHP.png')?>"
         accesskey=""border="0" alt="California Highway Patrol" width="351" height="105" style="background-color: #ddd"/><br/>
CHP Traffic Reports</a>
</p>
<p style="padding: 12px; text-align: center;">
<a href="https://www.nsc.org/"
   style="background: none;">
    <img src="<?php echo A25_Link::to('images/nsc.png')?>"
         accesskey=""border="0" alt="National Safety Council" width="161" height="68" /><br/>
National Safety Council</a>
</p>
<p style="padding: 12px; text-align: center;">
<a href="https://www.nhtsa.gov/"
   style="background: none;">
    <img src="<?php echo A25_Link::to('images/nhtsa.jpg')?>"
         accesskey=""border="0" alt="NHTSA" width="138" height="80" /><br/>
National Highway Traffic Safety Administration</a>
</p>
<p style="padding: 12px; text-align: center;">
<a href="https://www.dmv.ca.gov/portal/dmv/detail/dl/dl"
   style="background: none;">
    <img src="<?php echo A25_Link::to('images/cadmv.jpg')?>"
         accesskey=""border="0" alt="CA DMV" width="100" height="100" /><br/>
California Department of Motor Vehicles Drivers' information</a>
</p>
<p>Californiasafedriver.com provides these links as a resource to you. It in no way should indicate this as any type of endorsement.</p>