<div class="shell">
<div class="colHeader"><?php echo A25_DI::PlatformConfig()->contactUsTitle; ?></div>
<div class="colHeaderPic" style="max-height: 100%;">
	<img src="/images/SavingLives.png" border="0" alt="SavingLives.png" style="max-width: 100%;"/>
</div>
<div id="colContent">

<h2><?php echo PlatformConfig::agency ?></h2>
<?php echo PlatformConfig::contactUs() ?>

<span class="article_seperator">&nbsp;</span>
</div></div>
