<h2>Payment Policies</h2>
<p>All courses require payment with credit card within
<?php echo A25_DI::PlatformConfig()->kickOutAfterDeadline ?>.
<p>If payment is not received in time, your seat reservation will be lost and you will need to register again.</p>
<p>All payments are NON-REFUNDABLE and cannot be transferred to any other student account.</p>

<p>No payments are accepted at the class location.</p>

<h2>Payment Options</h2>

<p>Pay your tuition with a credit/debit card online or by calling
<?php echo PlatformConfig::phoneNumber ?>.  (<?php echo A25_DI::PlatformConfig()->acceptedCards ?> accepted)</p>

<p>If your form of payment is not approved by your financial institution,
an additional 
$<?php echo A25_DI::PlatformConfig()->nsfFee ?> NSF fee will apply.</p>
