<div class="shell">
<div class="colHeader"><?php echo A25_DI::PlatformConfig()->contactUsTitle; ?></div>
<div align="center">
<div class="colHeaderPic" style="background-color: #99BBFF">
	<img src="/images/headers/24.jpg" border="0" alt="24.jpg" style="max-width: 100%;"/><br /></div>
</div>
<div id="colContent">

<h2><?php echo PlatformConfig::agency ?></h2>
<?php echo PlatformConfig::contactUs() ?>

<span class="article_seperator">&nbsp;</span>
</div></div>
