<?php
$mainLocation = A25_Record_Location::retrieve(
		ServerConfig::parentLocationId);

// Pluralize late fee deadline
$late_fee_deadline = $mainLocation->late_fee_deadline / 24;
$late_fee_string = $late_fee_deadline . ' day';
if ($late_fee_deadline != 1) {
	$late_fee_string .= 's';
}
?>
<p><strong>Payment is due at least
<?php echo $late_fee_string; ?> before your class date.
A $<?php echo $mainLocation->late_fee ?> late fee is charged for any payments
not received <?php echo $late_fee_string; ?> in advance.
</strong></p>

<p>No payments are accepted at the class location.</p>

<p>Pay your tuition with a credit/debit card online or by calling
<?php echo PlatformConfig::phoneNumber ?></p>

<p>Or, mail a check or money order payable to <?php echo A25_DI::PlatformConfig()->paymentTo ?> to this address:</p>

<p><?php echo PlatformConfig::paymentAddressHtml() ?></p>

<p>Please include the student's name with your payment. If your check is
returned for non-payment, you will be charged an additional $<?php echo
$mainLocation->late_fee ?> late fee and $<?php echo
A25_DI::PlatformConfig()->nsfFee ?> NSF charge.</p>
